version: '3.9'

services:
  web:
    container_name: bbwheroes_web
    env_file: ./docker.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bbwheroes_web_node_modules:/app/node_modules
    networks:
      - bbwheroes

volumes:
  bbwheroes_web_node_modules:

networks:
  bbwheroes:
    external: true